alertmanager:
  enabled: false

server:
  persistentVolume:
    enabled: true
    size: 8Gi
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

pushgateway:
  enabled: false

nodeExporter:
  enabled: false
