apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: game-db
  namespace: lugx-gaming
spec:
  serviceName: "game-db"
  replicas: 1
  selector:
    matchLabels:
      app: game-db
  template:
    metadata:
      labels:
        app: game-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "game_db"
        - name: POSTGRES_USER
          value: "game_user"
        - name: POSTGRES_PASSWORD
          value: "game_password"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: game-db-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
  volumeClaimTemplates:
  - metadata:
      name: game-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
