apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: lugx-gaming
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytics-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: analytics-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: analytics-service
        image: rakavan/analytics-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: CLICKHOUSE_HOST
          value: "http://clickhouse:8123"
        - name: CLICKHOUSE_USERNAME
          valueFrom:
            secretKeyRef:
              name: clickhouse-secret
              key: username
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-secret
              key: password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
