apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: lugx-gaming
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: tcp
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
#        - name: clickhouse-users
#          mountPath: /etc/clickhouse-server/users.xml
#          subPath: users.xml
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
#      volumes:
#      - name: clickhouse-users
#        configMap:
#          name: clickhouse-users-xml
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessMod
